# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Checkout typst
              uses: actions/checkout@v4
              with:
                  repository: "typst/typst"
                  path: "typst"
            # checkout typst-jp repository
            - uses: actions/checkout@v4
              with:
                  repository: "typst-jp/typst-jp.github.io"
                  path: "typst-jp"
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: oven-sh/setup-bun@v2
            # build website
            - name: Build docs.json
              run: |
                  ./deploy.sh
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "typst-jp/website/dist"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
